## LIMPIEZA DE DATOS

In [4]:
import os  
import warnings
warnings.filterwarnings("ignore")
os.chdir("C:/Users/LUIS HERNANDEZ/Desktop/EBAC")
import pandas as pd
category = pd.read_csv("DIM_CATEGORY_F.csv")
product = pd.read_excel("DIM_PRODUCT_F.xlsx")
segment = pd.read_excel("DIM_SEGMENT_F.xlsx")
calendar = pd.read_excel("DIM_CALENDAR_F.xlsx")
sales = pd.read_csv("FACT_SALES_F.csv")

### CATEGORY

In [5]:
category

   ID_CATEGORY                        CATEGORY
0            1  FABRIC TREATMENT and SANIT\r\n
1            2                       AIR CARE
2            3                    LAVAVAJILLAS
3            4                MEGA SUPERFICIES
4            5             LAVATORY CARE & BRC

In [6]:
# Limpiar saltos de línea y caracteres no deseados en la columna 'CATEGORY'
category['CATEGORY'] = category['CATEGORY'].str.replace(r'[\r\n]', '', regex=True)  # Eliminar \r y \n
category

   ID_CATEGORY                    CATEGORY
0            1  FABRIC TREATMENT and SANIT
1            2                   AIR CARE
2            3                LAVAVAJILLAS
3            4            MEGA SUPERFICIES
4            5         LAVATORY CARE & BRC

In [7]:
# Eliminar espacios al inicio y final
category['CATEGORY'] = category['CATEGORY'].str.strip()  
category

   ID_CATEGORY                    CATEGORY
0            1  FABRIC TREATMENT and SANIT
1            2                    AIR CARE
2            3                LAVAVAJILLAS
3            4            MEGA SUPERFICIES
4            5         LAVATORY CARE & BRC

In [8]:
# Convertir el texto de la columna 'CATEGORY' a minúsculas (opcional, depende del análisis que quieras hacer)
category['CATEGORY'] = category['CATEGORY'].str.lower()
category

   ID_CATEGORY                    CATEGORY
0            1  fabric treatment and sanit
1            2                    air care
2            3                lavavajillas
3            4            mega superficies
4            5         lavatory care & brc

In [9]:
# Eliminar filas duplicadas (si las hubiera)
category = category.drop_duplicates()
category

   ID_CATEGORY                    CATEGORY
0            1  fabric treatment and sanit
1            2                    air care
2            3                lavavajillas
3            4            mega superficies
4            5         lavatory care & brc

In [10]:
# Comprobar si hay valores NaN en el DataFrame
if category.isnull().any().any():
    print("El DataFrame tiene valores faltantes.", category.isnull().sum())
else:
    print("El DataFrame no tiene valores faltantes.")

El DataFrame no tiene valores faltantes.

In [11]:
# Renombrar las columnas si es necesario
category

   ID_CATEGORY                    CATEGORY
0            1  fabric treatment and sanit
1            2                    air care
2            3                lavavajillas
3            4            mega superficies
4            5         lavatory care & brc

### PRODUCT

In [12]:
product

,MANUFACTURER,BRAND,ITEM,ITEM_DESCRIPTION,CATEGORY,FORMAT,ATTR1,ATTR2,ATTR3
0,INDS. ALEN,CLORALEX,0000075000592,CLORALEX EL RENDIDOR BOT.PLAST. 250ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
1,INDS. ALEN,CLORALEX,0000075000608,CLORALEX EL RENDIDOR BOT.PLAST. 500ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
2,INDS. ALEN,CLORALEX,0000075000615,CLORALEX EL RENDIDOR BOT.PLAST. 950ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
3,INDS. ALEN,CLORALEX,0000075000622,CLORALEX EL RENDIDOR BOT.PLAST. 2000ML NAL 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
4,INDS. ALEN,CLORALEX,0000075000639,CLORALEX EL RENDIDOR BOT.PLAST. 3750ML NAL 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
...,...,...,...,...,...,...,...,...,...
500,RECKITT,VANISH,7501058789778BP1,VANISH EXT HIGIENE REM MANCHAS GAL 4LT + VANIS...,1,LIQUIDO,SAFE BLEACH,FABRIC TREATMENT,ROSA
501,INDS. ALEN,CLORALEX,7501025412142,CLORALEX AROMAS BLANQUEADOR C/AROMA LAVANDA GA...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
502,INDS. ALEN,CLORALEX,NaN,CLORALEX EL RENDIDOR BOT PLAST 2LT,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
503,CLOROX,CLOROX,NaN,CLOROX MASCOTAS BLANQUEADOR+DETERGENTE GALON 10L,1,LIQUIDO,CLORO,CLORO,MASCOTAS
504,CLOROX,CLOROX,7502240948188BP1,CLOROX BLANQ930M+MMBLANQINOD709M+MMFIBRAULTRA1...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO

In [13]:
# 1. Eliminar filas con valores nulos en 'ITEM' y 'ITEM_DESCRIPTION'
# Esto puede depender de si se considera esencial o no, por ejemplo:
if product.isnull().any().any():
    print("El DataFrame tiene valores faltantes en:\n",product.isnull().sum())
else:
    print("El DataFrame no tiene valores faltantes.")

El DataFrame tiene valores faltantes en:
 MANUFACTURER        0
BRAND               0
ITEM                2
ITEM_DESCRIPTION    0
CATEGORY            0
FORMAT              0
ATTR1               6
ATTR2               0
ATTR3               6
dtype: int64

In [14]:
# 1. Eliminar filas con valores nulos en 'ITEM' y 'ITEM_DESCRIPTION'
# revisando la informcación, la cantidad de datos vacios no es significactiva, por lo que se optara por borrarla.:
product = product.dropna(subset=['ITEM'])
product

,MANUFACTURER,BRAND,ITEM,ITEM_DESCRIPTION,CATEGORY,FORMAT,ATTR1,ATTR2,ATTR3
0,INDS. ALEN,CLORALEX,0000075000592,CLORALEX EL RENDIDOR BOT.PLAST. 250ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
1,INDS. ALEN,CLORALEX,0000075000608,CLORALEX EL RENDIDOR BOT.PLAST. 500ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
2,INDS. ALEN,CLORALEX,0000075000615,CLORALEX EL RENDIDOR BOT.PLAST. 950ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
3,INDS. ALEN,CLORALEX,0000075000622,CLORALEX EL RENDIDOR BOT.PLAST. 2000ML NAL 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
4,INDS. ALEN,CLORALEX,0000075000639,CLORALEX EL RENDIDOR BOT.PLAST. 3750ML NAL 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
...,...,...,...,...,...,...,...,...,...
498,IBERIA,IBERIA,8411660210036,IBERIA REVOLUTION QUITA MANCHAS ACCIDENTALES B...,1,LIQUIDO,SAFE BLEACH,FABRIC TREATMENT,PRE LAVADOR
499,JABONERA LA ESPUMA,BCLORHADA,7501681101305BP1,BCLORHADA MASC DET DES C/CLOR1L+MM MASCHOGAR D...,1,LIQUIDO,CLORO,CLORO,MASCOTAS
500,RECKITT,VANISH,7501058789778BP1,VANISH EXT HIGIENE REM MANCHAS GAL 4LT + VANIS...,1,LIQUIDO,SAFE BLEACH,FABRIC TREATMENT,ROSA
501,INDS. ALEN,CLORALEX,7501025412142,CLORALEX AROMAS BLANQUEADOR C/AROMA LAVANDA GA...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
504,CLOROX,CLOROX,7502240948188BP1,CLOROX BLANQ930M+MMBLANQINOD709M+MMFIBRAULTRA1...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO

In [15]:
# Rellenar los valores nulos en 'ATTR3' con 'NO DEFINIDO'
product['ATTR3'].fillna('no definido')
product['ATTR1'].fillna('no definido')
product

,MANUFACTURER,BRAND,ITEM,ITEM_DESCRIPTION,CATEGORY,FORMAT,ATTR1,ATTR2,ATTR3
0,INDS. ALEN,CLORALEX,0000075000592,CLORALEX EL RENDIDOR BOT.PLAST. 250ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
1,INDS. ALEN,CLORALEX,0000075000608,CLORALEX EL RENDIDOR BOT.PLAST. 500ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
2,INDS. ALEN,CLORALEX,0000075000615,CLORALEX EL RENDIDOR BOT.PLAST. 950ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
3,INDS. ALEN,CLORALEX,0000075000622,CLORALEX EL RENDIDOR BOT.PLAST. 2000ML NAL 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
4,INDS. ALEN,CLORALEX,0000075000639,CLORALEX EL RENDIDOR BOT.PLAST. 3750ML NAL 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
...,...,...,...,...,...,...,...,...,...
498,IBERIA,IBERIA,8411660210036,IBERIA REVOLUTION QUITA MANCHAS ACCIDENTALES B...,1,LIQUIDO,SAFE BLEACH,FABRIC TREATMENT,PRE LAVADOR
499,JABONERA LA ESPUMA,BCLORHADA,7501681101305BP1,BCLORHADA MASC DET DES C/CLOR1L+MM MASCHOGAR D...,1,LIQUIDO,CLORO,CLORO,MASCOTAS
500,RECKITT,VANISH,7501058789778BP1,VANISH EXT HIGIENE REM MANCHAS GAL 4LT + VANIS...,1,LIQUIDO,SAFE BLEACH,FABRIC TREATMENT,ROSA
501,INDS. ALEN,CLORALEX,7501025412142,CLORALEX AROMAS BLANQUEADOR C/AROMA LAVANDA GA...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
504,CLOROX,CLOROX,7502240948188BP1,CLOROX BLANQ930M+MMBLANQINOD709M+MMFIBRAULTRA1...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO

In [16]:
# 2. Limpiar los textos, eliminar espacios adicionales y convertir a minúsculas
product.loc[:,'MANUFACTURER'] = product['MANUFACTURER'].str.strip().str.lower()
product.loc[:,'BRAND'] = product['BRAND'].str.strip().str.lower()
product.loc[:,'ITEM'] = product['ITEM'].str.strip().str.lower()
product.loc[:,'ITEM_DESCRIPTION'] = product['ITEM_DESCRIPTION'].str.strip().str.lower()
product.loc[:,'FORMAT'] = product['FORMAT'].str.strip().str.lower()
product.loc[:,'ATTR1'] = product['ATTR1'].str.strip().str.lower()
product.loc[:,'ATTR2'] = product['ATTR2'].str.strip().str.lower()
product.loc[:,'ATTR3'] = product['ATTR3'].str.strip().str.lower()
product

,MANUFACTURER,BRAND,ITEM,ITEM_DESCRIPTION,CATEGORY,FORMAT,ATTR1,ATTR2,ATTR3
0,inds. alen,cloralex,0000075000592,cloralex el rendidor bot.plast. 250ml nal. 000...,1,liquido,cloro,cloro,no definido
1,inds. alen,cloralex,0000075000608,cloralex el rendidor bot.plast. 500ml nal. 000...,1,liquido,cloro,cloro,no definido
2,inds. alen,cloralex,0000075000615,cloralex el rendidor bot.plast. 950ml nal. 000...,1,liquido,cloro,cloro,no definido
3,inds. alen,cloralex,0000075000622,cloralex el rendidor bot.plast. 2000ml nal 000...,1,liquido,cloro,cloro,no definido
4,inds. alen,cloralex,0000075000639,cloralex el rendidor bot.plast. 3750ml nal 000...,1,liquido,cloro,cloro,no definido
...,...,...,...,...,...,...,...,...,...
498,iberia,iberia,8411660210036,iberia revolution quita manchas accidentales b...,1,liquido,safe bleach,fabric treatment,pre lavador
499,jabonera la espuma,bclorhada,7501681101305bp1,bclorhada masc det des c/clor1l+mm maschogar d...,1,liquido,cloro,cloro,mascotas
500,reckitt,vanish,7501058789778bp1,vanish ext higiene rem manchas gal 4lt + vanis...,1,liquido,safe bleach,fabric treatment,rosa
501,inds. alen,cloralex,7501025412142,cloralex aromas blanqueador c/aroma lavanda ga...,1,liquido,cloro,cloro,no definido
504,clorox,clorox,7502240948188bp1,clorox blanq930m+mmblanqinod709m+mmfibraultra1...,1,liquido,cloro,cloro,no definido

In [17]:
# 3. Estandarizar valores en 'ATTR3' (por ejemplo, 'NO DEFINIDO' y 'ROSA')
# product.loc[:,'ATTR3'] = product['ATTR3'].replace({'rosa': 'color rosa', 'mascotas': 'productos mascotas'})
#product

In [18]:
# 4. Eliminar duplicados
product.duplicated().sum()
product = product.drop_duplicates()

In [19]:
if product.isnull().any().any():
    print("El DataFrame tiene valores faltantes.")
else:
    print("El DataFrame no tiene valores faltantes.")

El DataFrame tiene valores faltantes.

In [20]:
# Corregir tipos de datos: asegurarse de que 'CATEGORY' y 'FORMAT' sean categóricos si es necesario
product['CATEGORY'] = product['CATEGORY'].astype('category')
product['FORMAT'] = product['FORMAT'].astype('category')
product

,MANUFACTURER,BRAND,ITEM,ITEM_DESCRIPTION,CATEGORY,FORMAT,ATTR1,ATTR2,ATTR3
0,inds. alen,cloralex,0000075000592,cloralex el rendidor bot.plast. 250ml nal. 000...,1,liquido,cloro,cloro,no definido
1,inds. alen,cloralex,0000075000608,cloralex el rendidor bot.plast. 500ml nal. 000...,1,liquido,cloro,cloro,no definido
2,inds. alen,cloralex,0000075000615,cloralex el rendidor bot.plast. 950ml nal. 000...,1,liquido,cloro,cloro,no definido
3,inds. alen,cloralex,0000075000622,cloralex el rendidor bot.plast. 2000ml nal 000...,1,liquido,cloro,cloro,no definido
4,inds. alen,cloralex,0000075000639,cloralex el rendidor bot.plast. 3750ml nal 000...,1,liquido,cloro,cloro,no definido
...,...,...,...,...,...,...,...,...,...
498,iberia,iberia,8411660210036,iberia revolution quita manchas accidentales b...,1,liquido,safe bleach,fabric treatment,pre lavador
499,jabonera la espuma,bclorhada,7501681101305bp1,bclorhada masc det des c/clor1l+mm maschogar d...,1,liquido,cloro,cloro,mascotas
500,reckitt,vanish,7501058789778bp1,vanish ext higiene rem manchas gal 4lt + vanis...,1,liquido,safe bleach,fabric treatment,rosa
501,inds. alen,cloralex,7501025412142,cloralex aromas blanqueador c/aroma lavanda ga...,1,liquido,cloro,cloro,no definido
504,clorox,clorox,7502240948188bp1,clorox blanq930m+mmblanqinod709m+mmfibraultra1...,1,liquido,cloro,cloro,no definido

### SEGMENT

In [21]:
segment

,CATEGORY,ATTR1,ATTR2,ATTR3,FORMAT,SEGMENT
0,1,CLORO,CLORO,BAMBINO,LIQUIDO,BLEACH
1,1,CLORO,CLORO,GERMICIDA,LIQUIDO,BLEACH
2,1,CLORO,CLORO,MASCOTAS,LIQUIDO,BLEACH
3,1,CLORO,CLORO,MULTIUSOS,GEL,BLEACH
4,1,CLORO,CLORO,MULTIUSOS,LIQUIDO,BLEACH
5,1,CLORO,CLORO,NO DEFINIDO,LIQUIDO,BLEACH
6,1,CLORO,CLORO,NO DEFINIDO,POLVO,BLEACH
7,1,CLORO,CLORO,OTR. TIPOS,LIQUIDO,BLEACH
8,1,CLORO,CLORO,OTR. TIPOS,POLVO,BLEACH
9,1,CLORO,CLORO,ROPA BEBE,LIQUIDO,BLEACH
10,1,CLORO,CLORO,NaN,LIQUIDO,BLEACH
11,1,CLORO,MASCOTAS,MASCOTAS,LIQUIDO,BLEACH
12,1,CLORO,MULTIUSOS,MULTIUSOS,GEL,BLEACH
13,1,CLORO,NO DEFINIDO,NO DEFINIDO,LIQUIDO,BLEACH
14,1,PRELAVADOR,FABRIC TREATMENT,BLANCO,GEL,LIQUID & GEL
15,1,PRELAVADOR,FABRIC TREATMENT,BLANCO,POLVO,POWDER
16,1,PRELAVADOR,FABRIC TREATMENT,BLANCO,TOALLAS,OTHERS
17,1,PRELAVADOR,FABRIC TREATMENT,OTR. TIPOS,LIQUIDO,PRETREAT
18,1,PRELAVADOR,FABRIC TREATMENT,PRE LAVADOR,LIQUIDO,PRETREAT
19,1,PRELAVADOR,FABRIC TREATMENT,PRE LAVADOR,POLVO,POWDER
20,1,PRELAVADOR,FABRIC TREATMENT,QUITAMANCHAS,LIQUIDO,PRETREAT
21,1,PRELAVADOR,FABRIC TREATMENT,ROPA COLOR,LIQUIDO,PRETREAT
22,1,PRELAVADOR,FABRIC TREATMENT,ROSA,GEL,LIQUID & GEL
23,1,PRELAVADOR,FABRIC TREATMENT,ROSA,LIQUIDO,PRETREAT
24,1,PRELAVADOR,FABRIC TREATMENT,ROSA,POLVO,POWDER
25,1,SAFE BLEACH,FABRIC TREATMENT,BLANCO,BARRA,BAR
26,1,SAFE BLEACH,FABRIC TREATMENT,BLANCO,GEL,LIQUID & GEL
27,1,SAFE BLEACH,FABRIC TREATMENT,BLANCO,LIQUIDO,LIQUID & GEL
28,1,SAFE BLEACH,FABRIC TREATMENT,BLANCO,POLVO,POWDER
29,1,SAFE BLEACH,FABRIC TREATMENT,COLOR PODER VINAGRE,GEL,LIQUID & GEL
30,1,SAFE BLEACH,FABRIC TREATMENT,COLOR PODER VINAGRE,LIQUIDO,LIQUID & GEL
31,1,SAFE BLEACH,FABRIC TREATMENT,OTR. TIPOS,BARRA,BAR
32,1,SAFE BLEACH,FABRIC TREATMENT,OTR. TIPOS,GEL,LIQUID & GEL
33,1,SAFE BLEACH,FABRIC TREATMENT,OTR. TIPOS,LIQUIDO,LIQUID & GEL
34,1,SAFE BLEACH,FABRIC TREATMENT,OTR. TIPOS,POLVO,POWDER
35,1,SAFE BLEACH,FABRIC TREATMENT,PODER OXIGENO,GEL,LIQUID & GEL
36,1,SAFE BLEACH,FABRIC TREATMENT,PRE LAVADOR,BARRA,BAR
37,1,SAFE BLEACH,FABRIC TREATMENT,PRE LAVADOR,GEL,LIQUID & GEL
38,1,SAFE BLEACH,FABRIC TREATMENT,PRE LAVADOR,LIQUIDO,PRETREAT
39,1,SAFE BLEACH,FABRIC TREATMENT,PRE LAVADOR,POLVO,POWDER
40,1,SAFE BLEACH,FABRIC TREATMENT,QUITAMANCHAS,GEL,LIQUID & GEL
41,1,SAFE BLEACH,FABRIC TREATMENT,QUITAMANCHAS,LIQUIDO,LIQUID & GEL
42,1,SAFE BLEACH,FABRIC TREATMENT,QUITAMANCHAS,POLVO,POWDER
43,1,SAFE BLEACH,FABRIC TREATMENT,ROPA BLANCA,LIQUIDO,LIQUID & GEL
44,1,SAFE BLEACH,FABRIC TREATMENT,ROPA BLANCA,POLVO,POWDER
45,1,SAFE BLEACH,FABRIC TREATMENT,ROPA COLOR,LIQUIDO,LIQUID & GEL
46,1,SAFE BLEACH,FABRIC TREATMENT,ROPA COLOR,POLVO,POWDER
47,1,SAFE BLEACH,FABRIC TREATMENT,ROSA,BARRA,BAR
48,1,SAFE BLEACH,FABRIC TREATMENT,ROSA,GEL,LIQUID & GEL
49,1,SAFE BLEACH,FABRIC TREATMENT,ROSA,LIQUIDO,LIQUID & GEL
50,1,SAFE BLEACH,FABRIC TREATMENT,ROSA,POLVO,POWDER
51,1,SAFE BLEACH,PRE LAVADOR,PRE LAVADOR,GEL,PRETREAT
52,1,SANITIZANTE,SANITIZANTE,SANITIZANTE,LIQUIDO,SANITIZER

In [22]:
segment.info()

<class 'pandas.DataFrame'>
RangeIndex: 53 entries, 0 to 52
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   CATEGORY  53 non-null     int64
 1   ATTR1     53 non-null     str
 2   ATTR2     53 non-null     str
 3   ATTR3     52 non-null     str
 4   FORMAT    53 non-null     str
 5   SEGMENT   53 non-null     str
dtypes: int64(1), str(5)
memory usage: 2.6 KB

In [23]:
if segment.isnull().any().any():
    print("El DataFrame tiene valores faltantes.\n",segment.isnull().sum())
else:
    print("El DataFrame no tiene valores faltantes.")

El DataFrame tiene valores faltantes.
 CATEGORY    0
ATTR1       0
ATTR2       0
ATTR3       1
FORMAT      0
SEGMENT     0
dtype: int64

In [24]:
segment.duplicated().sum()

np.int64(0)

In [25]:
segment['ATTR3'].fillna('no definido')
segment

,CATEGORY,ATTR1,ATTR2,ATTR3,FORMAT,SEGMENT
0,1,CLORO,CLORO,BAMBINO,LIQUIDO,BLEACH
1,1,CLORO,CLORO,GERMICIDA,LIQUIDO,BLEACH
2,1,CLORO,CLORO,MASCOTAS,LIQUIDO,BLEACH
3,1,CLORO,CLORO,MULTIUSOS,GEL,BLEACH
4,1,CLORO,CLORO,MULTIUSOS,LIQUIDO,BLEACH
5,1,CLORO,CLORO,NO DEFINIDO,LIQUIDO,BLEACH
6,1,CLORO,CLORO,NO DEFINIDO,POLVO,BLEACH
7,1,CLORO,CLORO,OTR. TIPOS,LIQUIDO,BLEACH
8,1,CLORO,CLORO,OTR. TIPOS,POLVO,BLEACH
9,1,CLORO,CLORO,ROPA BEBE,LIQUIDO,BLEACH
10,1,CLORO,CLORO,NaN,LIQUIDO,BLEACH
11,1,CLORO,MASCOTAS,MASCOTAS,LIQUIDO,BLEACH
12,1,CLORO,MULTIUSOS,MULTIUSOS,GEL,BLEACH
13,1,CLORO,NO DEFINIDO,NO DEFINIDO,LIQUIDO,BLEACH
14,1,PRELAVADOR,FABRIC TREATMENT,BLANCO,GEL,LIQUID & GEL
15,1,PRELAVADOR,FABRIC TREATMENT,BLANCO,POLVO,POWDER
16,1,PRELAVADOR,FABRIC TREATMENT,BLANCO,TOALLAS,OTHERS
17,1,PRELAVADOR,FABRIC TREATMENT,OTR. TIPOS,LIQUIDO,PRETREAT
18,1,PRELAVADOR,FABRIC TREATMENT,PRE LAVADOR,LIQUIDO,PRETREAT
19,1,PRELAVADOR,FABRIC TREATMENT,PRE LAVADOR,POLVO,POWDER
20,1,PRELAVADOR,FABRIC TREATMENT,QUITAMANCHAS,LIQUIDO,PRETREAT
21,1,PRELAVADOR,FABRIC TREATMENT,ROPA COLOR,LIQUIDO,PRETREAT
22,1,PRELAVADOR,FABRIC TREATMENT,ROSA,GEL,LIQUID & GEL
23,1,PRELAVADOR,FABRIC TREATMENT,ROSA,LIQUIDO,PRETREAT
24,1,PRELAVADOR,FABRIC TREATMENT,ROSA,POLVO,POWDER
25,1,SAFE BLEACH,FABRIC TREATMENT,BLANCO,BARRA,BAR
26,1,SAFE BLEACH,FABRIC TREATMENT,BLANCO,GEL,LIQUID & GEL
27,1,SAFE BLEACH,FABRIC TREATMENT,BLANCO,LIQUIDO,LIQUID & GEL
28,1,SAFE BLEACH,FABRIC TREATMENT,BLANCO,POLVO,POWDER
29,1,SAFE BLEACH,FABRIC TREATMENT,COLOR PODER VINAGRE,GEL,LIQUID & GEL
30,1,SAFE BLEACH,FABRIC TREATMENT,COLOR PODER VINAGRE,LIQUIDO,LIQUID & GEL
31,1,SAFE BLEACH,FABRIC TREATMENT,OTR. TIPOS,BARRA,BAR
32,1,SAFE BLEACH,FABRIC TREATMENT,OTR. TIPOS,GEL,LIQUID & GEL
33,1,SAFE BLEACH,FABRIC TREATMENT,OTR. TIPOS,LIQUIDO,LIQUID & GEL
34,1,SAFE BLEACH,FABRIC TREATMENT,OTR. TIPOS,POLVO,POWDER
35,1,SAFE BLEACH,FABRIC TREATMENT,PODER OXIGENO,GEL,LIQUID & GEL
36,1,SAFE BLEACH,FABRIC TREATMENT,PRE LAVADOR,BARRA,BAR
37,1,SAFE BLEACH,FABRIC TREATMENT,PRE LAVADOR,GEL,LIQUID & GEL
38,1,SAFE BLEACH,FABRIC TREATMENT,PRE LAVADOR,LIQUIDO,PRETREAT
39,1,SAFE BLEACH,FABRIC TREATMENT,PRE LAVADOR,POLVO,POWDER
40,1,SAFE BLEACH,FABRIC TREATMENT,QUITAMANCHAS,GEL,LIQUID & GEL
41,1,SAFE BLEACH,FABRIC TREATMENT,QUITAMANCHAS,LIQUIDO,LIQUID & GEL
42,1,SAFE BLEACH,FABRIC TREATMENT,QUITAMANCHAS,POLVO,POWDER
43,1,SAFE BLEACH,FABRIC TREATMENT,ROPA BLANCA,LIQUIDO,LIQUID & GEL
44,1,SAFE BLEACH,FABRIC TREATMENT,ROPA BLANCA,POLVO,POWDER
45,1,SAFE BLEACH,FABRIC TREATMENT,ROPA COLOR,LIQUIDO,LIQUID & GEL
46,1,SAFE BLEACH,FABRIC TREATMENT,ROPA COLOR,POLVO,POWDER
47,1,SAFE BLEACH,FABRIC TREATMENT,ROSA,BARRA,BAR
48,1,SAFE BLEACH,FABRIC TREATMENT,ROSA,GEL,LIQUID & GEL
49,1,SAFE BLEACH,FABRIC TREATMENT,ROSA,LIQUIDO,LIQUID & GEL
50,1,SAFE BLEACH,FABRIC TREATMENT,ROSA,POLVO,POWDER
51,1,SAFE BLEACH,PRE LAVADOR,PRE LAVADOR,GEL,PRETREAT
52,1,SANITIZANTE,SANITIZANTE,SANITIZANTE,LIQUIDO,SANITIZER

In [26]:
# Normalizar texto (minúsculas, quitar espacios)
segment['ATTR1'] = segment['ATTR1'].str.strip().str.lower()
segment['ATTR2'] = segment['ATTR2'].str.strip().str.lower()
segment['ATTR3'] = segment['ATTR3'].str.strip().str.lower()
segment['FORMAT'] = segment['FORMAT'].str.strip().str.lower()
segment['SEGMENT'] = segment['SEGMENT'].str.strip().str.lower()
segment

,CATEGORY,ATTR1,ATTR2,ATTR3,FORMAT,SEGMENT
0,1,cloro,cloro,bambino,liquido,bleach
1,1,cloro,cloro,germicida,liquido,bleach
2,1,cloro,cloro,mascotas,liquido,bleach
3,1,cloro,cloro,multiusos,gel,bleach
4,1,cloro,cloro,multiusos,liquido,bleach
5,1,cloro,cloro,no definido,liquido,bleach
6,1,cloro,cloro,no definido,polvo,bleach
7,1,cloro,cloro,otr. tipos,liquido,bleach
8,1,cloro,cloro,otr. tipos,polvo,bleach
9,1,cloro,cloro,ropa bebe,liquido,bleach
10,1,cloro,cloro,NaN,liquido,bleach
11,1,cloro,mascotas,mascotas,liquido,bleach
12,1,cloro,multiusos,multiusos,gel,bleach
13,1,cloro,no definido,no definido,liquido,bleach
14,1,prelavador,fabric treatment,blanco,gel,liquid & gel
15,1,prelavador,fabric treatment,blanco,polvo,powder
16,1,prelavador,fabric treatment,blanco,toallas,others
17,1,prelavador,fabric treatment,otr. tipos,liquido,pretreat
18,1,prelavador,fabric treatment,pre lavador,liquido,pretreat
19,1,prelavador,fabric treatment,pre lavador,polvo,powder
20,1,prelavador,fabric treatment,quitamanchas,liquido,pretreat
21,1,prelavador,fabric treatment,ropa color,liquido,pretreat
22,1,prelavador,fabric treatment,rosa,gel,liquid & gel
23,1,prelavador,fabric treatment,rosa,liquido,pretreat
24,1,prelavador,fabric treatment,rosa,polvo,powder
25,1,safe bleach,fabric treatment,blanco,barra,bar
26,1,safe bleach,fabric treatment,blanco,gel,liquid & gel
27,1,safe bleach,fabric treatment,blanco,liquido,liquid & gel
28,1,safe bleach,fabric treatment,blanco,polvo,powder
29,1,safe bleach,fabric treatment,color poder vinagre,gel,liquid & gel
30,1,safe bleach,fabric treatment,color poder vinagre,liquido,liquid & gel
31,1,safe bleach,fabric treatment,otr. tipos,barra,bar
32,1,safe bleach,fabric treatment,otr. tipos,gel,liquid & gel
33,1,safe bleach,fabric treatment,otr. tipos,liquido,liquid & gel
34,1,safe bleach,fabric treatment,otr. tipos,polvo,powder
35,1,safe bleach,fabric treatment,poder oxigeno,gel,liquid & gel
36,1,safe bleach,fabric treatment,pre lavador,barra,bar
37,1,safe bleach,fabric treatment,pre lavador,gel,liquid & gel
38,1,safe bleach,fabric treatment,pre lavador,liquido,pretreat
39,1,safe bleach,fabric treatment,pre lavador,polvo,powder
40,1,safe bleach,fabric treatment,quitamanchas,gel,liquid & gel
41,1,safe bleach,fabric treatment,quitamanchas,liquido,liquid & gel
42,1,safe bleach,fabric treatment,quitamanchas,polvo,powder
43,1,safe bleach,fabric treatment,ropa blanca,liquido,liquid & gel
44,1,safe bleach,fabric treatment,ropa blanca,polvo,powder
45,1,safe bleach,fabric treatment,ropa color,liquido,liquid & gel
46,1,safe bleach,fabric treatment,ropa color,polvo,powder
47,1,safe bleach,fabric treatment,rosa,barra,bar
48,1,safe bleach,fabric treatment,rosa,gel,liquid & gel
49,1,safe bleach,fabric treatment,rosa,liquido,liquid & gel
50,1,safe bleach,fabric treatment,rosa,polvo,powder
51,1,safe bleach,pre lavador,pre lavador,gel,pretreat
52,1,sanitizante,sanitizante,sanitizante,liquido,sanitizer

In [27]:
# Reemplazar valores inconsistentes como 'otr. tipos'
segment['ATTR3'] = segment['ATTR3'].replace('otr. tipos', 'otros tipos')
segment

,CATEGORY,ATTR1,ATTR2,ATTR3,FORMAT,SEGMENT
0,1,cloro,cloro,bambino,liquido,bleach
1,1,cloro,cloro,germicida,liquido,bleach
2,1,cloro,cloro,mascotas,liquido,bleach
3,1,cloro,cloro,multiusos,gel,bleach
4,1,cloro,cloro,multiusos,liquido,bleach
5,1,cloro,cloro,no definido,liquido,bleach
6,1,cloro,cloro,no definido,polvo,bleach
7,1,cloro,cloro,otros tipos,liquido,bleach
8,1,cloro,cloro,otros tipos,polvo,bleach
9,1,cloro,cloro,ropa bebe,liquido,bleach
10,1,cloro,cloro,NaN,liquido,bleach
11,1,cloro,mascotas,mascotas,liquido,bleach
12,1,cloro,multiusos,multiusos,gel,bleach
13,1,cloro,no definido,no definido,liquido,bleach
14,1,prelavador,fabric treatment,blanco,gel,liquid & gel
15,1,prelavador,fabric treatment,blanco,polvo,powder
16,1,prelavador,fabric treatment,blanco,toallas,others
17,1,prelavador,fabric treatment,otros tipos,liquido,pretreat
18,1,prelavador,fabric treatment,pre lavador,liquido,pretreat
19,1,prelavador,fabric treatment,pre lavador,polvo,powder
20,1,prelavador,fabric treatment,quitamanchas,liquido,pretreat
21,1,prelavador,fabric treatment,ropa color,liquido,pretreat
22,1,prelavador,fabric treatment,rosa,gel,liquid & gel
23,1,prelavador,fabric treatment,rosa,liquido,pretreat
24,1,prelavador,fabric treatment,rosa,polvo,powder
25,1,safe bleach,fabric treatment,blanco,barra,bar
26,1,safe bleach,fabric treatment,blanco,gel,liquid & gel
27,1,safe bleach,fabric treatment,blanco,liquido,liquid & gel
28,1,safe bleach,fabric treatment,blanco,polvo,powder
29,1,safe bleach,fabric treatment,color poder vinagre,gel,liquid & gel
30,1,safe bleach,fabric treatment,color poder vinagre,liquido,liquid & gel
31,1,safe bleach,fabric treatment,otros tipos,barra,bar
32,1,safe bleach,fabric treatment,otros tipos,gel,liquid & gel
33,1,safe bleach,fabric treatment,otros tipos,liquido,liquid & gel
34,1,safe bleach,fabric treatment,otros tipos,polvo,powder
35,1,safe bleach,fabric treatment,poder oxigeno,gel,liquid & gel
36,1,safe bleach,fabric treatment,pre lavador,barra,bar
37,1,safe bleach,fabric treatment,pre lavador,gel,liquid & gel
38,1,safe bleach,fabric treatment,pre lavador,liquido,pretreat
39,1,safe bleach,fabric treatment,pre lavador,polvo,powder
40,1,safe bleach,fabric treatment,quitamanchas,gel,liquid & gel
41,1,safe bleach,fabric treatment,quitamanchas,liquido,liquid & gel
42,1,safe bleach,fabric treatment,quitamanchas,polvo,powder
43,1,safe bleach,fabric treatment,ropa blanca,liquido,liquid & gel
44,1,safe bleach,fabric treatment,ropa blanca,polvo,powder
45,1,safe bleach,fabric treatment,ropa color,liquido,liquid & gel
46,1,safe bleach,fabric treatment,ropa color,polvo,powder
47,1,safe bleach,fabric treatment,rosa,barra,bar
48,1,safe bleach,fabric treatment,rosa,gel,liquid & gel
49,1,safe bleach,fabric treatment,rosa,liquido,liquid & gel
50,1,safe bleach,fabric treatment,rosa,polvo,powder
51,1,safe bleach,pre lavador,pre lavador,gel,pretreat
52,1,sanitizante,sanitizante,sanitizante,liquido,sanitizer

In [28]:
# Corregir tipo de datos en 'CATEGORY' si es necesario
segment['CATEGORY'] = pd.to_numeric(segment['CATEGORY'], errors='coerce')
segment

,CATEGORY,ATTR1,ATTR2,ATTR3,FORMAT,SEGMENT
0,1,cloro,cloro,bambino,liquido,bleach
1,1,cloro,cloro,germicida,liquido,bleach
2,1,cloro,cloro,mascotas,liquido,bleach
3,1,cloro,cloro,multiusos,gel,bleach
4,1,cloro,cloro,multiusos,liquido,bleach
5,1,cloro,cloro,no definido,liquido,bleach
6,1,cloro,cloro,no definido,polvo,bleach
7,1,cloro,cloro,otros tipos,liquido,bleach
8,1,cloro,cloro,otros tipos,polvo,bleach
9,1,cloro,cloro,ropa bebe,liquido,bleach
10,1,cloro,cloro,NaN,liquido,bleach
11,1,cloro,mascotas,mascotas,liquido,bleach
12,1,cloro,multiusos,multiusos,gel,bleach
13,1,cloro,no definido,no definido,liquido,bleach
14,1,prelavador,fabric treatment,blanco,gel,liquid & gel
15,1,prelavador,fabric treatment,blanco,polvo,powder
16,1,prelavador,fabric treatment,blanco,toallas,others
17,1,prelavador,fabric treatment,otros tipos,liquido,pretreat
18,1,prelavador,fabric treatment,pre lavador,liquido,pretreat
19,1,prelavador,fabric treatment,pre lavador,polvo,powder
20,1,prelavador,fabric treatment,quitamanchas,liquido,pretreat
21,1,prelavador,fabric treatment,ropa color,liquido,pretreat
22,1,prelavador,fabric treatment,rosa,gel,liquid & gel
23,1,prelavador,fabric treatment,rosa,liquido,pretreat
24,1,prelavador,fabric treatment,rosa,polvo,powder
25,1,safe bleach,fabric treatment,blanco,barra,bar
26,1,safe bleach,fabric treatment,blanco,gel,liquid & gel
27,1,safe bleach,fabric treatment,blanco,liquido,liquid & gel
28,1,safe bleach,fabric treatment,blanco,polvo,powder
29,1,safe bleach,fabric treatment,color poder vinagre,gel,liquid & gel
30,1,safe bleach,fabric treatment,color poder vinagre,liquido,liquid & gel
31,1,safe bleach,fabric treatment,otros tipos,barra,bar
32,1,safe bleach,fabric treatment,otros tipos,gel,liquid & gel
33,1,safe bleach,fabric treatment,otros tipos,liquido,liquid & gel
34,1,safe bleach,fabric treatment,otros tipos,polvo,powder
35,1,safe bleach,fabric treatment,poder oxigeno,gel,liquid & gel
36,1,safe bleach,fabric treatment,pre lavador,barra,bar
37,1,safe bleach,fabric treatment,pre lavador,gel,liquid & gel
38,1,safe bleach,fabric treatment,pre lavador,liquido,pretreat
39,1,safe bleach,fabric treatment,pre lavador,polvo,powder
40,1,safe bleach,fabric treatment,quitamanchas,gel,liquid & gel
41,1,safe bleach,fabric treatment,quitamanchas,liquido,liquid & gel
42,1,safe bleach,fabric treatment,quitamanchas,polvo,powder
43,1,safe bleach,fabric treatment,ropa blanca,liquido,liquid & gel
44,1,safe bleach,fabric treatment,ropa blanca,polvo,powder
45,1,safe bleach,fabric treatment,ropa color,liquido,liquid & gel
46,1,safe bleach,fabric treatment,ropa color,polvo,powder
47,1,safe bleach,fabric treatment,rosa,barra,bar
48,1,safe bleach,fabric treatment,rosa,gel,liquid & gel
49,1,safe bleach,fabric treatment,rosa,liquido,liquid & gel
50,1,safe bleach,fabric treatment,rosa,polvo,powder
51,1,safe bleach,pre lavador,pre lavador,gel,pretreat
52,1,sanitizante,sanitizante,sanitizante,liquido,sanitizer

### CALENDAR

In [29]:
calendar

      WEEK  YEAR  MONTH  WEEK_NUMBER       DATE
0    01-21  2021      1            1 2021-01-10
1    02-21  2021      1            2 2021-01-17
2    03-21  2021      1            3 2021-01-24
3    04-21  2021      1            4 2021-01-31
4    05-21  2021      2            5 2021-02-07
..     ...   ...    ...          ...        ...
151  48-23  2023     12           48 2023-12-04
152  49-23  2023     12           49 2023-12-11
153  50-23  2023     12           50 2023-12-18
154  51-23  2023     12           51 2023-12-25
155  52-23  2023      1           52 2024-01-01

[156 rows x 5 columns]

In [30]:
# Verificar si hay valores nulos
if calendar.isnull().any().any():
    print("El DataFrame tiene valores faltantes en:\n",calendar.isnull().sum())
else:
    print("El DataFrame no tiene valores faltantes.")

El DataFrame no tiene valores faltantes.

In [31]:
# Verificar si hay duplicados
print(calendar.duplicated().sum())

0

In [32]:
calendar.info()

<class 'pandas.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   WEEK         156 non-null    str
 1   YEAR         156 non-null    int64
 2   MONTH        156 non-null    int64
 3   WEEK_NUMBER  156 non-null    int64
 4   DATE         156 non-null    datetime64[us]
dtypes: datetime64[us](1), int64(3), str(1)
memory usage: 6.2 KB

In [33]:
# Asegurar que 'YEAR' sea un número de 4 dígitos
calendar['YEAR'] = calendar['YEAR'].astype(str)
calendar['YEAR'] = calendar['YEAR'].apply(lambda x: x if len(x) == 4 else None)
# Convertir a número
calendar['YEAR'] = pd.to_numeric(calendar['YEAR'], errors='coerce')
calendar

      WEEK  YEAR  MONTH  WEEK_NUMBER       DATE
0    01-21  2021      1            1 2021-01-10
1    02-21  2021      1            2 2021-01-17
2    03-21  2021      1            3 2021-01-24
3    04-21  2021      1            4 2021-01-31
4    05-21  2021      2            5 2021-02-07
..     ...   ...    ...          ...        ...
151  48-23  2023     12           48 2023-12-04
152  49-23  2023     12           49 2023-12-11
153  50-23  2023     12           50 2023-12-18
154  51-23  2023     12           51 2023-12-25
155  52-23  2023      1           52 2024-01-01

[156 rows x 5 columns]

In [34]:
# Asegurar que el mes esté entre 1 y 12
calendar['MONTH'] = calendar['MONTH'].apply(lambda x: x if 1 <= x <= 12 else None)
calendar

      WEEK  YEAR  MONTH  WEEK_NUMBER       DATE
0    01-21  2021      1            1 2021-01-10
1    02-21  2021      1            2 2021-01-17
2    03-21  2021      1            3 2021-01-24
3    04-21  2021      1            4 2021-01-31
4    05-21  2021      2            5 2021-02-07
..     ...   ...    ...          ...        ...
151  48-23  2023     12           48 2023-12-04
152  49-23  2023     12           49 2023-12-11
153  50-23  2023     12           50 2023-12-18
154  51-23  2023     12           51 2023-12-25
155  52-23  2023      1           52 2024-01-01

[156 rows x 5 columns]

In [35]:
# Asegurar que el número de semana esté entre 1 y 53
calendar['WEEK_NUMBER'] = calendar['WEEK_NUMBER'].apply(lambda x: x if 1 <= x < 53 else None)
calendar

      WEEK  YEAR  MONTH  WEEK_NUMBER       DATE
0    01-21  2021      1            1 2021-01-10
1    02-21  2021      1            2 2021-01-17
2    03-21  2021      1            3 2021-01-24
3    04-21  2021      1            4 2021-01-31
4    05-21  2021      2            5 2021-02-07
..     ...   ...    ...          ...        ...
151  48-23  2023     12           48 2023-12-04
152  49-23  2023     12           49 2023-12-11
153  50-23  2023     12           50 2023-12-18
154  51-23  2023     12           51 2023-12-25
155  52-23  2023      1           52 2024-01-01

[156 rows x 5 columns]

In [36]:
# Extraer el número de semana y año de la columna 'WEEK'
calendar_ext = calendar['WEEK_NUMBER_EXTRACTED'] = calendar['WEEK'].apply(lambda x: int(x.split('-')[0]))
calendar_year = calendar['YEAR_EXTRACTED'] = calendar['WEEK'].apply(lambda x: int(x.split('-')[1]))

# Verificar si la fecha corresponde a la semana indicada
calendar['DATE_WEEK'] = calendar['DATE'].dt.isocalendar().week

# Comprobar si el número de semana extraído coincide con el de la columna 'WEEK_NUMBER'
calendar['WEEK_CHECK'] = calendar['WEEK_NUMBER'] == calendar['DATE_WEEK']

# Verificar si hay inconsistencias
calendar[calendar['WEEK_CHECK'] == False]

,WEEK,YEAR,MONTH,WEEK_NUMBER,DATE,WEEK_NUMBER_EXTRACTED,YEAR_EXTRACTED,DATE_WEEK,WEEK_CHECK
104,01-23,2023,1,1,2023-01-09,1,23,2,False
105,02-23,2023,1,2,2023-01-16,2,23,3,False
106,03-23,2023,1,3,2023-01-23,3,23,4,False
107,04-23,2023,1,4,2023-01-30,4,23,5,False
108,05-23,2023,2,5,2023-02-06,5,23,6,False
109,06-23,2023,2,6,2023-02-13,6,23,7,False
110,07-23,2023,2,7,2023-02-20,7,23,8,False
111,08-23,2023,2,8,2023-02-27,8,23,9,False
112,09-23,2023,3,9,2023-03-06,9,23,10,False
113,10-23,2023,3,10,2023-03-13,10,23,11,False
114,11-23,2023,3,11,2023-03-20,11,23,12,False
115,12-23,2023,3,12,2023-03-27,12,23,13,False
116,13-23,2023,4,13,2023-04-03,13,23,14,False
117,14-23,2023,4,14,2023-04-10,14,23,15,False
118,15-23,2023,4,15,2023-04-17,15,23,16,False
119,16-23,2023,4,16,2023-04-24,16,23,17,False
120,17-23,2023,5,17,2023-05-01,17,23,18,False
121,18-23,2023,5,18,2023-05-08,18,23,19,False
122,19-23,2023,5,19,2023-05-15,19,23,20,False
123,20-23,2023,5,20,2023-05-22,20,23,21,False
124,21-23,2023,5,21,2023-05-29,21,23,22,False
125,22-23,2023,6,22,2023-06-05,22,23,23,False
126,23-23,2023,6,23,2023-06-12,23,23,24,False
127,24-23,2023,6,24,2023-06-19,24,23,25,False
128,25-23,2023,6,25,2023-06-26,25,23,26,False
129,26-23,2023,7,26,2023-07-03,26,23,27,False
130,27-23,2023,7,27,2023-07-10,27,23,28,False
131,28-23,2023,7,28,2023-07-17,28,23,29,False
132,29-23,2023,7,29,2023-07-24,29,23,30,False
133,30-23,2023,7,30,2023-07-31,30,23,31,False
134,31-23,2023,8,31,2023-08-07,31,23,32,False
135,32-23,2023,8,32,2023-08-14,32,23,33,False
136,33-23,2023,8,33,2023-08-21,33,23,34,False
137,34-23,2023,8,34,2023-08-28,34,23,35,False
138,35-23,2023,9,35,2023-09-04,35,23,36,False
139,36-23,2023,9,36,2023-09-11,36,23,37,False
140,37-23,2023,9,37,2023-09-18,37,23,38,False
141,38-23,2023,9,38,2023-09-25,38,23,39,False
142,39-23,2023,10,39,2023-10-02,39,23,40,False
143,40-23,2023,10,40,2023-10-09,40,23,41,False
144,41-23,2023,10,41,2023-10-16,41,23,42,False
145,42-23,2023,10,42,2023-10-23,42,23,43,False
146,43-23,2023,10,43,2023-10-30,43,23,44,False
147,44-23,2023,11,44,2023-11-06,44,23,45,False
148,45-23,2023,11,45,2023-11-13,45,23,46,False
149,46-23,2023,11,46,2023-11-20,46,23,47,False
150,47-23,2023,11,47,2023-11-27,47,23,48,False
151,48-23,2023,12,48,2023-12-04,48,23,49,False
152,49-23,2023,12,49,2023-12-11,49,23,50,False
153,50-23,2023,12,50,2023-12-18,50,23,51,False
154,51-23,2023,12,51,2023-12-25,51,23,52,False
155,52-23,2023,1,52,2024-01-01,52,23,1,False

In [37]:
calendar

,WEEK,YEAR,MONTH,WEEK_NUMBER,DATE,WEEK_NUMBER_EXTRACTED,YEAR_EXTRACTED,DATE_WEEK,WEEK_CHECK
0,01-21,2021,1,1,2021-01-10,1,21,1,True
1,02-21,2021,1,2,2021-01-17,2,21,2,True
2,03-21,2021,1,3,2021-01-24,3,21,3,True
3,04-21,2021,1,4,2021-01-31,4,21,4,True
4,05-21,2021,2,5,2021-02-07,5,21,5,True
...,...,...,...,...,...,...,...,...,...
151,48-23,2023,12,48,2023-12-04,48,23,49,False
152,49-23,2023,12,49,2023-12-11,49,23,50,False
153,50-23,2023,12,50,2023-12-18,50,23,51,False
154,51-23,2023,12,51,2023-12-25,51,23,52,False
155,52-23,2023,1,52,2024-01-01,52,23,1,False

### SALES

In [38]:
sales

,WEEK,ITEM_CODE,TOTAL_UNIT_SALES,TOTAL_VALUE_SALES,TOTAL_UNIT_AVG_WEEKLY_SALES,REGION
0,34-22,7501058792808BP2,0.006,0.139,1.000,TOTAL AUTOS AREA 5
1,34-22,7501058715883,0.487,116.519,2.916,TOTAL AUTOS AREA 5
2,34-22,7702626213774,1.391,68.453,5.171,TOTAL AUTOS AREA 5
3,34-22,7501058716422,0.022,1.481,1.833,TOTAL AUTOS AREA 5
4,34-22,7501058784353,2.037,182.839,5.375,TOTAL AUTOS AREA 5
...,...,...,...,...,...,...
121997,26-23,7501058792778BP1,1.192,150.829,4.000,TOTAL AUTOS SCANNING MEXICO
121998,26-23,7501058757630,1.947,235.416,2.797,TOTAL AUTOS SCANNING MEXICO
121999,26-23,7501058753441,18.013,429.289,9.102,TOTAL AUTOS SCANNING MEXICO
122000,26-23,7702626204208BP1,21.152,210.276,22.172,TOTAL AUTOS SCANNING MEXICO
122001,26-23,7501058784346,1.468,301.973,2.068,TOTAL AUTOS SCANNING MEXICO

In [39]:
sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 122002 entries, 0 to 122001
Data columns (total 6 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   WEEK                         122002 non-null  str
 1   ITEM_CODE                    122002 non-null  str
 2   TOTAL_UNIT_SALES             122002 non-null  float64
 3   TOTAL_VALUE_SALES            122002 non-null  float64
 4   TOTAL_UNIT_AVG_WEEKLY_SALES  122002 non-null  float64
 5   REGION                       122002 non-null  str
dtypes: float64(3), str(3)
memory usage: 5.6 MB

In [40]:
sales.describe()

       TOTAL_UNIT_SALES  TOTAL_VALUE_SALES  TOTAL_UNIT_AVG_WEEKLY_SALES
count     122002.000000      122002.000000                122002.000000
mean           3.211097          90.513761                    10.099904
std           14.496009         350.236505                    22.650142
min            0.000000           0.001000                     0.042000
25%            0.063000           2.662000                     2.316000
50%            0.367000          16.812000                     3.993500
75%            1.520000          62.961500                     8.898000
max          504.681000       12236.759000                   794.000000

In [41]:
sales.isnull().sum()

WEEK                           0
ITEM_CODE                      0
TOTAL_UNIT_SALES               0
TOTAL_VALUE_SALES              0
TOTAL_UNIT_AVG_WEEKLY_SALES    0
REGION                         0
dtype: int64

In [42]:
sales.duplicated().sum()

np.int64(0)

In [43]:
# Eliminar espacios extra en los nombres de las columnas
sales.columns = sales.columns.str.strip()

# Mostrar los nuevos nombres de las columnas
sales.columns

Index(['WEEK', 'ITEM_CODE', 'TOTAL_UNIT_SALES', 'TOTAL_VALUE_SALES',
       'TOTAL_UNIT_AVG_WEEKLY_SALES', 'REGION'],
      dtype='str')

In [44]:
calendar

,WEEK,YEAR,MONTH,WEEK_NUMBER,DATE,WEEK_NUMBER_EXTRACTED,YEAR_EXTRACTED,DATE_WEEK,WEEK_CHECK
0,01-21,2021,1,1,2021-01-10,1,21,1,True
1,02-21,2021,1,2,2021-01-17,2,21,2,True
2,03-21,2021,1,3,2021-01-24,3,21,3,True
3,04-21,2021,1,4,2021-01-31,4,21,4,True
4,05-21,2021,2,5,2021-02-07,5,21,5,True
...,...,...,...,...,...,...,...,...,...
151,48-23,2023,12,48,2023-12-04,48,23,49,False
152,49-23,2023,12,49,2023-12-11,49,23,50,False
153,50-23,2023,12,50,2023-12-18,50,23,51,False
154,51-23,2023,12,51,2023-12-25,51,23,52,False
155,52-23,2023,1,52,2024-01-01,52,23,1,False

In [45]:
sales

,WEEK,ITEM_CODE,TOTAL_UNIT_SALES,TOTAL_VALUE_SALES,TOTAL_UNIT_AVG_WEEKLY_SALES,REGION
0,34-22,7501058792808BP2,0.006,0.139,1.000,TOTAL AUTOS AREA 5
1,34-22,7501058715883,0.487,116.519,2.916,TOTAL AUTOS AREA 5
2,34-22,7702626213774,1.391,68.453,5.171,TOTAL AUTOS AREA 5
3,34-22,7501058716422,0.022,1.481,1.833,TOTAL AUTOS AREA 5
4,34-22,7501058784353,2.037,182.839,5.375,TOTAL AUTOS AREA 5
...,...,...,...,...,...,...
121997,26-23,7501058792778BP1,1.192,150.829,4.000,TOTAL AUTOS SCANNING MEXICO
121998,26-23,7501058757630,1.947,235.416,2.797,TOTAL AUTOS SCANNING MEXICO
121999,26-23,7501058753441,18.013,429.289,9.102,TOTAL AUTOS SCANNING MEXICO
122000,26-23,7702626204208BP1,21.152,210.276,22.172,TOTAL AUTOS SCANNING MEXICO
122001,26-23,7501058784346,1.468,301.973,2.068,TOTAL AUTOS SCANNING MEXICO

In [46]:
product

,MANUFACTURER,BRAND,ITEM,ITEM_DESCRIPTION,CATEGORY,FORMAT,ATTR1,ATTR2,ATTR3
0,inds. alen,cloralex,0000075000592,cloralex el rendidor bot.plast. 250ml nal. 000...,1,liquido,cloro,cloro,no definido
1,inds. alen,cloralex,0000075000608,cloralex el rendidor bot.plast. 500ml nal. 000...,1,liquido,cloro,cloro,no definido
2,inds. alen,cloralex,0000075000615,cloralex el rendidor bot.plast. 950ml nal. 000...,1,liquido,cloro,cloro,no definido
3,inds. alen,cloralex,0000075000622,cloralex el rendidor bot.plast. 2000ml nal 000...,1,liquido,cloro,cloro,no definido
4,inds. alen,cloralex,0000075000639,cloralex el rendidor bot.plast. 3750ml nal 000...,1,liquido,cloro,cloro,no definido
...,...,...,...,...,...,...,...,...,...
498,iberia,iberia,8411660210036,iberia revolution quita manchas accidentales b...,1,liquido,safe bleach,fabric treatment,pre lavador
499,jabonera la espuma,bclorhada,7501681101305bp1,bclorhada masc det des c/clor1l+mm maschogar d...,1,liquido,cloro,cloro,mascotas
500,reckitt,vanish,7501058789778bp1,vanish ext higiene rem manchas gal 4lt + vanis...,1,liquido,safe bleach,fabric treatment,rosa
501,inds. alen,cloralex,7501025412142,cloralex aromas blanqueador c/aroma lavanda ga...,1,liquido,cloro,cloro,no definido
504,clorox,clorox,7502240948188bp1,clorox blanq930m+mmblanqinod709m+mmfibraultra1...,1,liquido,cloro,cloro,no definido

In [47]:
segment

,CATEGORY,ATTR1,ATTR2,ATTR3,FORMAT,SEGMENT
0,1,cloro,cloro,bambino,liquido,bleach
1,1,cloro,cloro,germicida,liquido,bleach
2,1,cloro,cloro,mascotas,liquido,bleach
3,1,cloro,cloro,multiusos,gel,bleach
4,1,cloro,cloro,multiusos,liquido,bleach
5,1,cloro,cloro,no definido,liquido,bleach
6,1,cloro,cloro,no definido,polvo,bleach
7,1,cloro,cloro,otros tipos,liquido,bleach
8,1,cloro,cloro,otros tipos,polvo,bleach
9,1,cloro,cloro,ropa bebe,liquido,bleach
10,1,cloro,cloro,NaN,liquido,bleach
11,1,cloro,mascotas,mascotas,liquido,bleach
12,1,cloro,multiusos,multiusos,gel,bleach
13,1,cloro,no definido,no definido,liquido,bleach
14,1,prelavador,fabric treatment,blanco,gel,liquid & gel
15,1,prelavador,fabric treatment,blanco,polvo,powder
16,1,prelavador,fabric treatment,blanco,toallas,others
17,1,prelavador,fabric treatment,otros tipos,liquido,pretreat
18,1,prelavador,fabric treatment,pre lavador,liquido,pretreat
19,1,prelavador,fabric treatment,pre lavador,polvo,powder
20,1,prelavador,fabric treatment,quitamanchas,liquido,pretreat
21,1,prelavador,fabric treatment,ropa color,liquido,pretreat
22,1,prelavador,fabric treatment,rosa,gel,liquid & gel
23,1,prelavador,fabric treatment,rosa,liquido,pretreat
24,1,prelavador,fabric treatment,rosa,polvo,powder
25,1,safe bleach,fabric treatment,blanco,barra,bar
26,1,safe bleach,fabric treatment,blanco,gel,liquid & gel
27,1,safe bleach,fabric treatment,blanco,liquido,liquid & gel
28,1,safe bleach,fabric treatment,blanco,polvo,powder
29,1,safe bleach,fabric treatment,color poder vinagre,gel,liquid & gel
30,1,safe bleach,fabric treatment,color poder vinagre,liquido,liquid & gel
31,1,safe bleach,fabric treatment,otros tipos,barra,bar
32,1,safe bleach,fabric treatment,otros tipos,gel,liquid & gel
33,1,safe bleach,fabric treatment,otros tipos,liquido,liquid & gel
34,1,safe bleach,fabric treatment,otros tipos,polvo,powder
35,1,safe bleach,fabric treatment,poder oxigeno,gel,liquid & gel
36,1,safe bleach,fabric treatment,pre lavador,barra,bar
37,1,safe bleach,fabric treatment,pre lavador,gel,liquid & gel
38,1,safe bleach,fabric treatment,pre lavador,liquido,pretreat
39,1,safe bleach,fabric treatment,pre lavador,polvo,powder
40,1,safe bleach,fabric treatment,quitamanchas,gel,liquid & gel
41,1,safe bleach,fabric treatment,quitamanchas,liquido,liquid & gel
42,1,safe bleach,fabric treatment,quitamanchas,polvo,powder
43,1,safe bleach,fabric treatment,ropa blanca,liquido,liquid & gel
44,1,safe bleach,fabric treatment,ropa blanca,polvo,powder
45,1,safe bleach,fabric treatment,ropa color,liquido,liquid & gel
46,1,safe bleach,fabric treatment,ropa color,polvo,powder
47,1,safe bleach,fabric treatment,rosa,barra,bar
48,1,safe bleach,fabric treatment,rosa,gel,liquid & gel
49,1,safe bleach,fabric treatment,rosa,liquido,liquid & gel
50,1,safe bleach,fabric treatment,rosa,polvo,powder
51,1,safe bleach,pre lavador,pre lavador,gel,pretreat
52,1,sanitizante,sanitizante,sanitizante,liquido,sanitizer

In [48]:
category

   ID_CATEGORY                    CATEGORY
0            1  fabric treatment and sanit
1            2                    air care
2            3                lavavajillas
3            4            mega superficies
4            5         lavatory care & brc

In [49]:
df_marged = pd.merge(sales, product, left_on='ITEM_CODE', right_on='ITEM', how = 'inner')
df_marged

,WEEK,ITEM_CODE,TOTAL_UNIT_SALES,TOTAL_VALUE_SALES,TOTAL_UNIT_AVG_WEEKLY_SALES,REGION,MANUFACTURER,BRAND,ITEM,ITEM_DESCRIPTION,CATEGORY,FORMAT,ATTR1,ATTR2,ATTR3
0,34-22,7501058715883,0.487,116.519,2.916,TOTAL AUTOS AREA 5,reckitt,vanish,7501058715883,vanish oxi action gold quitamanchas bolsa 1.8k...,1,polvo,safe bleach,fabric treatment,rosa
1,34-22,7702626213774,1.391,68.453,5.171,TOTAL AUTOS AREA 5,reckitt,vanish,7702626213774,vanish oxi action rosa quitamanchas doypack 24...,1,polvo,safe bleach,fabric treatment,rosa
2,34-22,7501058716422,0.022,1.481,1.833,TOTAL AUTOS AREA 5,reckitt,vanish,7501058716422,vanish oxi action gold quitamancha ahorro del ...,1,polvo,safe bleach,fabric treatment,rosa
3,34-22,7501058784353,2.037,182.839,5.375,TOTAL AUTOS AREA 5,reckitt,vanish,7501058784353,vanish intelligence polvo bote 450 gr nal 7501...,1,polvo,safe bleach,fabric treatment,rosa
4,34-22,7501058716064,0.005,0.679,1.250,TOTAL AUTOS AREA 5,reckitt,vanish,7501058716064,vanish oxi action rosa quita/manchas p/ropa bo...,1,polvo,safe bleach,fabric treatment,rosa
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112804,26-23,7501058784353,5.737,612.956,2.951,TOTAL AUTOS SCANNING MEXICO,reckitt,vanish,7501058784353,vanish intelligence polvo bote 450 gr nal 7501...,1,polvo,safe bleach,fabric treatment,rosa
112805,26-23,7501058716064,0.246,38.758,1.906,TOTAL AUTOS SCANNING MEXICO,reckitt,vanish,7501058716064,vanish oxi action rosa quita/manchas p/ropa bo...,1,polvo,safe bleach,fabric treatment,rosa
112806,26-23,7501058757630,1.947,235.416,2.797,TOTAL AUTOS SCANNING MEXICO,reckitt,vanish,7501058757630,vanish poder o2 pre-lavador bot.atom. 650 ml n...,1,liquido,prelavador,fabric treatment,rosa
112807,26-23,7501058753441,18.013,429.289,9.102,TOTAL AUTOS SCANNING MEXICO,reckitt,vanish,7501058753441,vanish poder o2 doypack 120 gr 7501058753441,1,polvo,safe bleach,fabric treatment,rosa
112808,26-23,7501058784346,1.468,301.973,2.068,TOTAL AUTOS SCANNING MEXICO,reckitt,vanish,7501058784346,vanish poder 02 intelligence polvo bot 900 gr ...,1,polvo,safe bleach,fabric treatment,rosa

In [50]:
df_marged.duplicated().sum()

np.int64(0)

In [51]:
df_marged_cat = pd.merge(df_marged, category, left_on='CATEGORY', right_on='ID_CATEGORY', how='left')
df_marged_cat

,WEEK,ITEM_CODE,TOTAL_UNIT_SALES,TOTAL_VALUE_SALES,TOTAL_UNIT_AVG_WEEKLY_SALES,REGION,MANUFACTURER,BRAND,ITEM,ITEM_DESCRIPTION,CATEGORY_x,FORMAT,ATTR1,ATTR2,ATTR3,ID_CATEGORY,CATEGORY_y
0,34-22,7501058715883,0.487,116.519,2.916,TOTAL AUTOS AREA 5,reckitt,vanish,7501058715883,vanish oxi action gold quitamanchas bolsa 1.8k...,1,polvo,safe bleach,fabric treatment,rosa,1,fabric treatment and sanit
1,34-22,7702626213774,1.391,68.453,5.171,TOTAL AUTOS AREA 5,reckitt,vanish,7702626213774,vanish oxi action rosa quitamanchas doypack 24...,1,polvo,safe bleach,fabric treatment,rosa,1,fabric treatment and sanit
2,34-22,7501058716422,0.022,1.481,1.833,TOTAL AUTOS AREA 5,reckitt,vanish,7501058716422,vanish oxi action gold quitamancha ahorro del ...,1,polvo,safe bleach,fabric treatment,rosa,1,fabric treatment and sanit
3,34-22,7501058784353,2.037,182.839,5.375,TOTAL AUTOS AREA 5,reckitt,vanish,7501058784353,vanish intelligence polvo bote 450 gr nal 7501...,1,polvo,safe bleach,fabric treatment,rosa,1,fabric treatment and sanit
4,34-22,7501058716064,0.005,0.679,1.250,TOTAL AUTOS AREA 5,reckitt,vanish,7501058716064,vanish oxi action rosa quita/manchas p/ropa bo...,1,polvo,safe bleach,fabric treatment,rosa,1,fabric treatment and sanit
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112804,26-23,7501058784353,5.737,612.956,2.951,TOTAL AUTOS SCANNING MEXICO,reckitt,vanish,7501058784353,vanish intelligence polvo bote 450 gr nal 7501...,1,polvo,safe bleach,fabric treatment,rosa,1,fabric treatment and sanit
112805,26-23,7501058716064,0.246,38.758,1.906,TOTAL AUTOS SCANNING MEXICO,reckitt,vanish,7501058716064,vanish oxi action rosa quita/manchas p/ropa bo...,1,polvo,safe bleach,fabric treatment,rosa,1,fabric treatment and sanit
112806,26-23,7501058757630,1.947,235.416,2.797,TOTAL AUTOS SCANNING MEXICO,reckitt,vanish,7501058757630,vanish poder o2 pre-lavador bot.atom. 650 ml n...,1,liquido,prelavador,fabric treatment,rosa,1,fabric treatment and sanit
112807,26-23,7501058753441,18.013,429.289,9.102,TOTAL AUTOS SCANNING MEXICO,reckitt,vanish,7501058753441,vanish poder o2 doypack 120 gr 7501058753441,1,polvo,safe bleach,fabric treatment,rosa,1,fabric treatment and sanit
112808,26-23,7501058784346,1.468,301.973,2.068,TOTAL AUTOS SCANNING MEXICO,reckitt,vanish,7501058784346,vanish poder 02 intelligence polvo bot 900 gr ...,1,polvo,safe bleach,fabric treatment,rosa,1,fabric treatment and sanit

In [52]:
df_marged_cat.isnull().sum()

WEEK                           0
ITEM_CODE                      0
TOTAL_UNIT_SALES               0
TOTAL_VALUE_SALES              0
TOTAL_UNIT_AVG_WEEKLY_SALES    0
REGION                         0
MANUFACTURER                   0
BRAND                          0
ITEM                           0
ITEM_DESCRIPTION               0
CATEGORY_x                     0
FORMAT                         0
ATTR1                          0
ATTR2                          0
ATTR3                          0
ID_CATEGORY                    0
CATEGORY_y                     0
dtype: int64

In [53]:
df_final = pd.merge(df_marged_cat, segment, left_on=['CATEGORY_x','FORMAT','ATTR1','ATTR2','ATTR3'], right_on=['CATEGORY','FORMAT','ATTR1','ATTR2','ATTR3'], how='left') 
df_final

,WEEK,ITEM_CODE,TOTAL_UNIT_SALES,TOTAL_VALUE_SALES,TOTAL_UNIT_AVG_WEEKLY_SALES,REGION,MANUFACTURER,BRAND,ITEM,ITEM_DESCRIPTION,CATEGORY_x,FORMAT,ATTR1,ATTR2,ATTR3,ID_CATEGORY,CATEGORY_y,CATEGORY,SEGMENT
0,34-22,7501058715883,0.487,116.519,2.916,TOTAL AUTOS AREA 5,reckitt,vanish,7501058715883,vanish oxi action gold quitamanchas bolsa 1.8k...,1,polvo,safe bleach,fabric treatment,rosa,1,fabric treatment and sanit,1,powder
1,34-22,7702626213774,1.391,68.453,5.171,TOTAL AUTOS AREA 5,reckitt,vanish,7702626213774,vanish oxi action rosa quitamanchas doypack 24...,1,polvo,safe bleach,fabric treatment,rosa,1,fabric treatment and sanit,1,powder
2,34-22,7501058716422,0.022,1.481,1.833,TOTAL AUTOS AREA 5,reckitt,vanish,7501058716422,vanish oxi action gold quitamancha ahorro del ...,1,polvo,safe bleach,fabric treatment,rosa,1,fabric treatment and sanit,1,powder
3,34-22,7501058784353,2.037,182.839,5.375,TOTAL AUTOS AREA 5,reckitt,vanish,7501058784353,vanish intelligence polvo bote 450 gr nal 7501...,1,polvo,safe bleach,fabric treatment,rosa,1,fabric treatment and sanit,1,powder
4,34-22,7501058716064,0.005,0.679,1.250,TOTAL AUTOS AREA 5,reckitt,vanish,7501058716064,vanish oxi action rosa quita/manchas p/ropa bo...,1,polvo,safe bleach,fabric treatment,rosa,1,fabric treatment and sanit,1,powder
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112804,26-23,7501058784353,5.737,612.956,2.951,TOTAL AUTOS SCANNING MEXICO,reckitt,vanish,7501058784353,vanish intelligence polvo bote 450 gr nal 7501...,1,polvo,safe bleach,fabric treatment,rosa,1,fabric treatment and sanit,1,powder
112805,26-23,7501058716064,0.246,38.758,1.906,TOTAL AUTOS SCANNING MEXICO,reckitt,vanish,7501058716064,vanish oxi action rosa quita/manchas p/ropa bo...,1,polvo,safe bleach,fabric treatment,rosa,1,fabric treatment and sanit,1,powder
112806,26-23,7501058757630,1.947,235.416,2.797,TOTAL AUTOS SCANNING MEXICO,reckitt,vanish,7501058757630,vanish poder o2 pre-lavador bot.atom. 650 ml n...,1,liquido,prelavador,fabric treatment,rosa,1,fabric treatment and sanit,1,pretreat
112807,26-23,7501058753441,18.013,429.289,9.102,TOTAL AUTOS SCANNING MEXICO,reckitt,vanish,7501058753441,vanish poder o2 doypack 120 gr 7501058753441,1,polvo,safe bleach,fabric treatment,rosa,1,fabric treatment and sanit,1,powder
112808,26-23,7501058784346,1.468,301.973,2.068,TOTAL AUTOS SCANNING MEXICO,reckitt,vanish,7501058784346,vanish poder 02 intelligence polvo bot 900 gr ...,1,polvo,safe bleach,fabric treatment,rosa,1,fabric treatment and sanit,1,powder

In [54]:
df_final.isnull().sum()

WEEK                           0
ITEM_CODE                      0
TOTAL_UNIT_SALES               0
TOTAL_VALUE_SALES              0
TOTAL_UNIT_AVG_WEEKLY_SALES    0
REGION                         0
MANUFACTURER                   0
BRAND                          0
ITEM                           0
ITEM_DESCRIPTION               0
CATEGORY_x                     0
FORMAT                         0
ATTR1                          0
ATTR2                          0
ATTR3                          0
ID_CATEGORY                    0
CATEGORY_y                     0
CATEGORY                       0
SEGMENT                        0
dtype: int64

In [55]:
df_final.duplicated().sum()

np.int64(0)

In [56]:
df_final.drop_duplicates(inplace=True)
df_final

,WEEK,ITEM_CODE,TOTAL_UNIT_SALES,TOTAL_VALUE_SALES,TOTAL_UNIT_AVG_WEEKLY_SALES,REGION,MANUFACTURER,BRAND,ITEM,ITEM_DESCRIPTION,CATEGORY_x,FORMAT,ATTR1,ATTR2,ATTR3,ID_CATEGORY,CATEGORY_y,CATEGORY,SEGMENT
0,34-22,7501058715883,0.487,116.519,2.916,TOTAL AUTOS AREA 5,reckitt,vanish,7501058715883,vanish oxi action gold quitamanchas bolsa 1.8k...,1,polvo,safe bleach,fabric treatment,rosa,1,fabric treatment and sanit,1,powder
1,34-22,7702626213774,1.391,68.453,5.171,TOTAL AUTOS AREA 5,reckitt,vanish,7702626213774,vanish oxi action rosa quitamanchas doypack 24...,1,polvo,safe bleach,fabric treatment,rosa,1,fabric treatment and sanit,1,powder
2,34-22,7501058716422,0.022,1.481,1.833,TOTAL AUTOS AREA 5,reckitt,vanish,7501058716422,vanish oxi action gold quitamancha ahorro del ...,1,polvo,safe bleach,fabric treatment,rosa,1,fabric treatment and sanit,1,powder
3,34-22,7501058784353,2.037,182.839,5.375,TOTAL AUTOS AREA 5,reckitt,vanish,7501058784353,vanish intelligence polvo bote 450 gr nal 7501...,1,polvo,safe bleach,fabric treatment,rosa,1,fabric treatment and sanit,1,powder
4,34-22,7501058716064,0.005,0.679,1.250,TOTAL AUTOS AREA 5,reckitt,vanish,7501058716064,vanish oxi action rosa quita/manchas p/ropa bo...,1,polvo,safe bleach,fabric treatment,rosa,1,fabric treatment and sanit,1,powder
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112804,26-23,7501058784353,5.737,612.956,2.951,TOTAL AUTOS SCANNING MEXICO,reckitt,vanish,7501058784353,vanish intelligence polvo bote 450 gr nal 7501...,1,polvo,safe bleach,fabric treatment,rosa,1,fabric treatment and sanit,1,powder
112805,26-23,7501058716064,0.246,38.758,1.906,TOTAL AUTOS SCANNING MEXICO,reckitt,vanish,7501058716064,vanish oxi action rosa quita/manchas p/ropa bo...,1,polvo,safe bleach,fabric treatment,rosa,1,fabric treatment and sanit,1,powder
112806,26-23,7501058757630,1.947,235.416,2.797,TOTAL AUTOS SCANNING MEXICO,reckitt,vanish,7501058757630,vanish poder o2 pre-lavador bot.atom. 650 ml n...,1,liquido,prelavador,fabric treatment,rosa,1,fabric treatment and sanit,1,pretreat
112807,26-23,7501058753441,18.013,429.289,9.102,TOTAL AUTOS SCANNING MEXICO,reckitt,vanish,7501058753441,vanish poder o2 doypack 120 gr 7501058753441,1,polvo,safe bleach,fabric treatment,rosa,1,fabric treatment and sanit,1,powder
112808,26-23,7501058784346,1.468,301.973,2.068,TOTAL AUTOS SCANNING MEXICO,reckitt,vanish,7501058784346,vanish poder 02 intelligence polvo bot 900 gr ...,1,polvo,safe bleach,fabric treatment,rosa,1,fabric treatment and sanit,1,powder

In [57]:
df_final.drop(columns=['CATEGORY_x','ID_CATEGORY'], inplace=True)

In [58]:
df_final

,WEEK,ITEM_CODE,TOTAL_UNIT_SALES,TOTAL_VALUE_SALES,TOTAL_UNIT_AVG_WEEKLY_SALES,REGION,MANUFACTURER,BRAND,ITEM,ITEM_DESCRIPTION,FORMAT,ATTR1,ATTR2,ATTR3,CATEGORY_y,CATEGORY,SEGMENT
0,34-22,7501058715883,0.487,116.519,2.916,TOTAL AUTOS AREA 5,reckitt,vanish,7501058715883,vanish oxi action gold quitamanchas bolsa 1.8k...,polvo,safe bleach,fabric treatment,rosa,fabric treatment and sanit,1,powder
1,34-22,7702626213774,1.391,68.453,5.171,TOTAL AUTOS AREA 5,reckitt,vanish,7702626213774,vanish oxi action rosa quitamanchas doypack 24...,polvo,safe bleach,fabric treatment,rosa,fabric treatment and sanit,1,powder
2,34-22,7501058716422,0.022,1.481,1.833,TOTAL AUTOS AREA 5,reckitt,vanish,7501058716422,vanish oxi action gold quitamancha ahorro del ...,polvo,safe bleach,fabric treatment,rosa,fabric treatment and sanit,1,powder
3,34-22,7501058784353,2.037,182.839,5.375,TOTAL AUTOS AREA 5,reckitt,vanish,7501058784353,vanish intelligence polvo bote 450 gr nal 7501...,polvo,safe bleach,fabric treatment,rosa,fabric treatment and sanit,1,powder
4,34-22,7501058716064,0.005,0.679,1.250,TOTAL AUTOS AREA 5,reckitt,vanish,7501058716064,vanish oxi action rosa quita/manchas p/ropa bo...,polvo,safe bleach,fabric treatment,rosa,fabric treatment and sanit,1,powder
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112804,26-23,7501058784353,5.737,612.956,2.951,TOTAL AUTOS SCANNING MEXICO,reckitt,vanish,7501058784353,vanish intelligence polvo bote 450 gr nal 7501...,polvo,safe bleach,fabric treatment,rosa,fabric treatment and sanit,1,powder
112805,26-23,7501058716064,0.246,38.758,1.906,TOTAL AUTOS SCANNING MEXICO,reckitt,vanish,7501058716064,vanish oxi action rosa quita/manchas p/ropa bo...,polvo,safe bleach,fabric treatment,rosa,fabric treatment and sanit,1,powder
112806,26-23,7501058757630,1.947,235.416,2.797,TOTAL AUTOS SCANNING MEXICO,reckitt,vanish,7501058757630,vanish poder o2 pre-lavador bot.atom. 650 ml n...,liquido,prelavador,fabric treatment,rosa,fabric treatment and sanit,1,pretreat
112807,26-23,7501058753441,18.013,429.289,9.102,TOTAL AUTOS SCANNING MEXICO,reckitt,vanish,7501058753441,vanish poder o2 doypack 120 gr 7501058753441,polvo,safe bleach,fabric treatment,rosa,fabric treatment and sanit,1,powder
112808,26-23,7501058784346,1.468,301.973,2.068,TOTAL AUTOS SCANNING MEXICO,reckitt,vanish,7501058784346,vanish poder 02 intelligence polvo bot 900 gr ...,polvo,safe bleach,fabric treatment,rosa,fabric treatment and sanit,1,powder

In [ ]:
df_final.rename(columns={'CATEGORY_y': 'CATEGORY_DESCRIPTION'}, inplace=True)

In [60]:
df_final

,WEEK,ITEM_CODE,TOTAL_UNIT_SALES,TOTAL_VALUE_SALES,TOTAL_UNIT_AVG_WEEKLY_SALES,REGION,MANUFACTURER,BRAND,ITEM,ITEM_DESCRIPTION,FORMAT,ATTR1,ATTR2,ATTR3,CATEGORY_DESCRIPTION,CATEGORY,SEGMENT
0,34-22,7501058715883,0.487,116.519,2.916,TOTAL AUTOS AREA 5,reckitt,vanish,7501058715883,vanish oxi action gold quitamanchas bolsa 1.8k...,polvo,safe bleach,fabric treatment,rosa,fabric treatment and sanit,1,powder
1,34-22,7702626213774,1.391,68.453,5.171,TOTAL AUTOS AREA 5,reckitt,vanish,7702626213774,vanish oxi action rosa quitamanchas doypack 24...,polvo,safe bleach,fabric treatment,rosa,fabric treatment and sanit,1,powder
2,34-22,7501058716422,0.022,1.481,1.833,TOTAL AUTOS AREA 5,reckitt,vanish,7501058716422,vanish oxi action gold quitamancha ahorro del ...,polvo,safe bleach,fabric treatment,rosa,fabric treatment and sanit,1,powder
3,34-22,7501058784353,2.037,182.839,5.375,TOTAL AUTOS AREA 5,reckitt,vanish,7501058784353,vanish intelligence polvo bote 450 gr nal 7501...,polvo,safe bleach,fabric treatment,rosa,fabric treatment and sanit,1,powder
4,34-22,7501058716064,0.005,0.679,1.250,TOTAL AUTOS AREA 5,reckitt,vanish,7501058716064,vanish oxi action rosa quita/manchas p/ropa bo...,polvo,safe bleach,fabric treatment,rosa,fabric treatment and sanit,1,powder
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112804,26-23,7501058784353,5.737,612.956,2.951,TOTAL AUTOS SCANNING MEXICO,reckitt,vanish,7501058784353,vanish intelligence polvo bote 450 gr nal 7501...,polvo,safe bleach,fabric treatment,rosa,fabric treatment and sanit,1,powder
112805,26-23,7501058716064,0.246,38.758,1.906,TOTAL AUTOS SCANNING MEXICO,reckitt,vanish,7501058716064,vanish oxi action rosa quita/manchas p/ropa bo...,polvo,safe bleach,fabric treatment,rosa,fabric treatment and sanit,1,powder
112806,26-23,7501058757630,1.947,235.416,2.797,TOTAL AUTOS SCANNING MEXICO,reckitt,vanish,7501058757630,vanish poder o2 pre-lavador bot.atom. 650 ml n...,liquido,prelavador,fabric treatment,rosa,fabric treatment and sanit,1,pretreat
112807,26-23,7501058753441,18.013,429.289,9.102,TOTAL AUTOS SCANNING MEXICO,reckitt,vanish,7501058753441,vanish poder o2 doypack 120 gr 7501058753441,polvo,safe bleach,fabric treatment,rosa,fabric treatment and sanit,1,powder
112808,26-23,7501058784346,1.468,301.973,2.068,TOTAL AUTOS SCANNING MEXICO,reckitt,vanish,7501058784346,vanish poder 02 intelligence polvo bot 900 gr ...,polvo,safe bleach,fabric treatment,rosa,fabric treatment and sanit,1,powder

In [61]:
df_final.info()

<class 'pandas.DataFrame'>
RangeIndex: 112809 entries, 0 to 112808
Data columns (total 17 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   WEEK                         112809 non-null  str
 1   ITEM_CODE                    112809 non-null  str
 2   TOTAL_UNIT_SALES             112809 non-null  float64
 3   TOTAL_VALUE_SALES            112809 non-null  float64
 4   TOTAL_UNIT_AVG_WEEKLY_SALES  112809 non-null  float64
 5   REGION                       112809 non-null  str
 6   MANUFACTURER                 112809 non-null  str
 7   BRAND                        112809 non-null  str
 8   ITEM                         112809 non-null  str
 9   ITEM_DESCRIPTION             112809 non-null  str
 10  FORMAT                       112809 non-null  str
 11  ATTR1                        112809 non-null  str
 12  ATTR2                        112809 non-null  str
 13  ATTR3                        112809 non-null  str
 14  CATEGORY_DESCRIPTION         112809 non-null  object
 15  CATEGORY                     112809 non-null  int64
 16  SEGMENT                      112809 non-null  str
dtypes: float64(3), int64(1), object(1), str(12)
memory usage: 14.6+ MB

In [62]:
df_final.to_csv('entregable 1.csv', index=False)

In [63]:
df_final.to_excel('entregable 1.xlsx', index=False)